// Interface Product
import { IProduct } from "../../../types/product.type"

const products: IProduct[] = [
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
  {
    label: "Label",
    title: "UX Review Presentations",
    price: 40000,
    discount: 10,
    value: 450,
    fileName: "bottle",
  },
]

export default products